### ISSUE TITLE
XLConnectJars for R 3.1 issues

### ISSUE THREAD

**Issue by f1nasf1** [miraisolutions/xlconnectjars#1]
Hi,

Using R 3.1.3 install.packages("xlconnect") gives the following error when it tries to install the dependency:

Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'XLConnectJars/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

Appreciate any help in resolving this issue!

Thanks.

platform       x86_64-w64-mingw32  
arch           x86_64  
os             mingw32  
system         x86_64, mingw32  
status  
major          3  
minor          1.3  
year           2015  
month          03  
day            09  
svn rev        67962  
language       R  
version.string R version 3.1.3 (2015-03-09)
nickname       Smooth Sidewalk

**Comment by f1nasf1** [comment]
The 3.1 version zip file - XLConnectJars_0.2-9.zip -  seems to be corrupted

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/XLConnectJars_0.2-9.zip'
Content type 'application/zip' length 12947625 bytes (12.3 MB)
opened URL
downloaded 12.3 MB

Warning in install.packages :
  downloaded length 12931072 != reported length 12947625

**Comment by martinstuder** [comment]
The zip is fine and not corrupted. The issue you observe is most likely due to a corporate firewall which corrupts the download. You may get in touch with your IT to resolve the issue.
