### ISSUE TITLE
Java version check erring out for the new Java version

### ISSUE THREAD

**Issue by CH-hajukim** [miraisolutions/xlconnectjars#2]
Hi @martinstuder ,

Java version check code appears to be erring out for the latest Java version (10). 
I'm getting the following error message when trying to run this part of the script: 

<img width="559" alt="screen shot 2018-03-21 at 1 26 38 pm" src="https://user-images.githubusercontent.com/34696951/37735642-eeab0b9c-2d0b-11e8-9d3e-e1a23e5b06ef.png">

Could you please fix this as soon as possible? 
Thank you so much! 

#############################################################################
#
# XLConnectJars Package Initialization
# 
# Author: Martin Studer, Mirai Solutions GmbH
[#]([url](url))
#############################################################################

.onLoad <- function(libname, pkgname) {
	# Load Java dependencies (all jars inside the java subfolder)
	.jpackage(name = pkgname, jars = "*")
  
  # Java version check
  jv <- .jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
  if(substr(jv, 1L, 1L) == "1") {
    jvn <- as.numeric(paste0(strsplit(jv, "[.]")[[1L]][1:2], collapse = "."))
    if(jvn < 1.6) stop("Java 6 or higher is needed for this package")
  }
}

**Comment by martinstuder** [comment]
XLConnect 0.2-15 (depending on XLConnectJars 0.2-15) is on its way to CRAN

**Comment by CH-hajukim** [comment]
Perfect! Thank you @martinstuder.
